### ISSUE TITLE
RSDP reporting

### ISSUE THREAD

**Issue by genderev** [rust-osdev/bootloader#152]
```
rsdp_addr: Optional<u64>

The address of the RSDP data structure, which can be use to find the ACPI tables.

This field is None if no RSDP was found (for BIOS) or reported (for UEFI).
```
In what situation is RSDP not reported? If the RSDP is important to your kernel, is there any way to guarantee it will be `u64` and not `None`?

```
let gop = unsafe { &mut *gop.get() }; 
```

What is the purpose of the above line from `src/bin/uefi.rs`?

**Comment by bjorn3** [comment]
> In what situation is RSDP not reported? If the RSDP is important to your kernel, is there any way to guarantee it will be u64 and not None?

No RSDP is reported when the firmware doesn't support ACPI for whatever reason. For example because it is too old.

> What is the purpose of the above line from `src/bin/uefi.rs`?

`gop` is of type `&UnsafeCell<GraphicsOutput>`. This line converts it to `&mut GraphicsOutput` which is unsafe as it requires that there exists no other reference to the same location of a type unless it is also an `&UnsafeCell<GraphicsOutput>`.

**Comment by genderev** [comment]
Thank you for clarifying. 

Can you perform an operation such as `let gop = unsafe { &mut *gop.get() };` for other boot services or is this specific to the graphics protocol?

**Comment by bjorn3** [comment]
It would work with any boot service. Just be careful to not have more than one non `&UnsafeCell<T>` reference to each boot service at any given time.

**Comment by genderev** [comment]
Thanks. I hope it is okay if I ask questions later as they arise - I have read a lot about UEFI but most documentation is in C.
