### ISSUE TITLE
Failed to add interrupt handling on top of the basic example

### ISSUE THREAD

**Issue by trusch** [rust-osdev/bootloader#190]
I tried to follow the blog_os blog up to chapter 6, but started from the basic example of this repo, so that I'm on the latest version of the bootloader crate. Everything works like a charm until after adding the gdt and Pic and I get a first timer interrupt. The handler is successfully called and calls IRET for the interrupt in the end. After that I get a double fault.

Could this be interacting with the serial output that I also setup like in the blog posts? Is there anything different while the bootloader stage that I need to consider?

I would be grateful for any thought on this. If needed I can push my current state and paste a link here.

Perhaps @phil-opp himself has an idea? :) 

edit: The code in question is here: https://github.com/trusch/snakeos

edit2: I somehow doubt that its a problem with an unregistered interrupt handler (at least for the interrupts from the PICS). I masked everything but not the timer interrupt and still get the double fault: `PICS.lock().write_masks(0b11111110, 0xFF);`

edit3: I'm getting a general_protection_error exception after the first timer interrupt. That one is not caused by a missing interrupt handler in the IDT, because I added handlers for all the predefined interrupts + handlers for all 16 possible PIC interrupts.

**Comment by lassipulkkinen** [comment]
I hit this problem a while ago after upgrading my existing project to bootloader 0.10.0, and have just now managed to solve it (I discovered this issue because I was looking for it). Apparently, the `iret` fails because the `ss` (stack segment) register points to the descriptor at GDT offset `0x10`, which isn't a data segment. Previous bootloader versions have set that register to `0x00`, which (I think) is always valid in ring 0. (This probably should've been mentioned in the changelog...)

blog_os doesn't include a data segment in its GDT, so it won't reload `ss` after the `lgdt`, either (although perhaps it should). Consequently, the "visible" value of `ss` is invalid with respect to the new GDT, but the processor is actually using its "hidden" copy of the segment descriptor, which is still valid. However, the validity of the register *is* checked when `iret` tries to pop its value from the stack, resulting in the error.

It follows that either adding a data segment to the GDT and loading that into `ss` and `ds`, or just loading `0x00` instead, fixes the problem.

**Comment by trusch** [comment]
@lassipulkkinen Thank you so much, I guess it would have taken ages to figure that out by myself. Indeed adding a kernel data segment and storing it in SS solved the issue.
