### ISSUE TITLE
Cant write to 0xB8000 or any address without it crashing 

### ISSUE THREAD

**Issue by salmmanfred** [rust-osdev/bootloader#233]
has the system changed for 0.9 and what am I suppose to do to be able to write to 0xB8000 ?

**Comment by phil-opp** [comment]
See https://os.phil-opp.com/vga-text-mode/ for instructions on how to write to the VGA text buffer in `bootloader v0.9`. For `v0.10` and `v0.11`, we use a pixel-based framebuffer instead of the VGA text mode. See our [migration guides](https://github.com/rust-osdev/bootloader/tree/main/docs/migration) for details.
