### ISSUE TITLE
Confusion about lgdt

### ISSUE THREAD

**Issue by jiangbo** [rust-osdev/bootloader#276]
in src/asm/stage_1.s

```asm
...
   lgdt [gdt32info]
...
gdt32info:
   .word gdt32_end - gdt32 - 1  # last byte in table
   .word gdt32  
gdt32:
    # entry 0 is always unused
    .quad 0
...
```
Does this mean that gdt is only two words length? But some sources say that gdtr should have 48 bits:
https://docs.oracle.com/cd/E19455-01/806-3773/instructionset-82/index.html

**Comment by Freax13** [comment]
The gdtr is 5 bytes for 16 bit mode, the two `.words` are indeed not enough, there should be an additional byte. In this case this works because the GDT is placed directly after the `gdt32info` and so the first byte of the zero entry of the GDT acts also happens to overlap with the last byte of `gdt32info`.

**Comment by jiangbo** [comment]
Oh, it uses the first byte of the zero entry of the GDT.
