### ISSUE TITLE
Support position independent code in higher half

### ISSUE THREAD

**Issue by phil-opp** [rust-osdev/bootloader#285]
When a PIC kernel is located in higher half, we currently try to allocate 33554177 entries in the level 4 page table, which of course fails. This is the reason that we currently use the `static` relocation model for our higher half test:

https://github.com/rust-osdev/bootloader/blob/4e2b8d7e4b4fad3c7aefd7f8174f86ec2119ecc7/Cargo.toml#L87

I think the issue is in these lines:

https://github.com/rust-osdev/bootloader/blob/4e2b8d7e4b4fad3c7aefd7f8174f86ec2119ecc7/common/src/load_kernel.rs#L64-L75

Looks like we only consider the end address for the size calculation, without taking the start address into account. I think we should be able to fix this by using the difference between the max and min address as size instead.

**Comment by phil-opp** [comment]
cc @Freax13

**Comment by phil-opp** [comment]
I started to look into this in <https://github.com/rust-osdev/bootloader/tree/higher-half-pic>. Not sure if my approach is right, though. The current error is "the relocation table must end in the elf file".

**Comment by Freax13** [comment]
Unless I'm missing something, specifying a image base address for a PIC kernel is meaningless because they're supposed to be able to be relocated anywhere. Instead the `dynamic_start` config value should be used (and already is for our higher half kernel test). 
Removing those two lines should do the trick:
https://github.com/rust-osdev/bootloader/blob/17ba81613b2feb55ca9d7be67a8923cb703d4511/Cargo.toml#L96-L97

**Comment by Freax13** [comment]
I'll take a look at your approach of changing how we calculate the size later today.

**Comment by phil-opp** [comment]
Thanks a lot! This issue is not that urgent, so no hurry. 

> Unless I'm missing something, specifying a image base address for a PIC kernel is meaningless because they're supposed to be able to be relocated anywhere.

I guess there are different possible ways to handle this. For example, we could try to default to the image base address if it's still free when ASLR is disabled. Or we could treat it as a fallback for the `dynamic_start` if it isn't specified. Or we just ignore it.

Either way, we should not panic on PIC kernels with a higher half base address. It should be possible to change the relocation mode without adjusting all addresses in a linker script.

**Comment by Freax13** [comment]
> I guess there are different possible ways to handle this. For example, we could try to default to the image base address if it's still free when ASLR is disabled. Or we could treat it as a fallback for the `dynamic_start` if it isn't specified. Or we just ignore it.

There is some precedence for treating the base address as the default: glibc used to treat the base address as the preferred address for PIEs when the `LD_USE_LOAD_BIAS` environment variable was set to `1`. This was used in conjunction with [prelinking](https://linux.die.net/man/8/prelink) which is a process that assigns static load addresses to shared libraries and PIEs at build time. Prelinking isn't used anymore which is my `LD_USE_LOAD_BIAS` was removed from glibc earlier this year. 

> Either way, we should not panic on PIC kernels with a higher half base address. It should be possible to change the relocation mode without adjusting all addresses in a linker script.

Agreed.

**Comment by Freax13** [comment]
> The current error is "the relocation table must end in the elf file".

We currently assume that the address given by the `RELA` entry is an offset into the file. This is incorrect, it's actually a virtual address pointing to mapped memory. The fix for this isn't entirely trivial because we need to translate the virtual address to a physical address (or in other words we need to translate from the kernel's address space to the bootloader's address space). I'm working on a fix.
