### ISSUE TITLE
Last page of stack memory is not used

### ISSUE THREAD

**Issue by phil-opp** [rust-osdev/bootloader#294]
We set the `stack_top` to the start address of the `stack_end` page here: https://github.com/rust-osdev/bootloader/blob/669e3c031f6ee6ad0cbe3f7d09e1b62e8bc34ff1/common/src/lib.rs#L485

However, it looks like `stack_end` is an inclusive bound: https://github.com/rust-osdev/bootloader/blob/669e3c031f6ee6ad0cbe3f7d09e1b62e8bc34ff1/common/src/lib.rs#L183-L186

So I think the stack pointer should be initialized with `(stack_end + 1).start_address()` instead.

Reported by `klim` on the Discord of [Theseus OS](https://www.theseus-os.com/).

**Comment by inhibitor1217** [comment]
It would be a lot of help if this issue is fixed soon. 

I'm currently working with a setup which assigns a single page (4 KiB) for the stack of each thread, including the kernel thread. Currently, last page (which is, the only page) of the stack is not used, causing the page fault to occur immediately after we jump to the kernel.

**Comment by phil-opp** [comment]
@inhibitor1217 Thanks for the reminder! I'll prepare a PR.
