### ISSUE TITLE
Mutable BootInfo

### ISSUE THREAD

**Issue by skyne98** [rust-osdev/bootloader#38]
Hey there! I have a question and, maybe, a suggestion: should bootinfo be passed as a mutable static reference? Or maybe there is no need at all for it to be a static reference? Maybe the struct itself should just contain the address (which can be easily copied) and all the other copies of bootinfo can operate on it during the function calls?

Right now, there seems to be a slight problem / inconvenience, where you cannot allocate any physical frames, because you have a static immutable reference to the bootinfo struct, which contains the required structs / functions.

Cheers, Alex!

**Comment by skyne98** [comment]
Also, I think that as a part of this issue is using the FrameAllocator - you just cannot create an instance of it, because it requires to "consume" a mutable reference to memory map. Wouldn't it be much simpler with copying / locks?

**Comment by phil-opp** [comment]
Hi! So you want to implement a frame allocator on top of the passed memory map? Or do you mean some existing frame allocator?

The problem with using the memory map is that it's just a simple slice backed by a fixed size array (maximal 64 entries). So you'll quickly run out of space when you create too many distinct regions. It is also not very efficient, since everything is O(n).

Instead of modifying the bootinfo, I would create a FrameAllocator on top of it that stores its information in kernel memory. A simple example is the bump allocator described in the first edition of the "Writing an OS in Rust" series: <https://os.phil-opp.com/allocating-frames/#a-frame-allocator>. It uses GRUB2 instead of `bootloader`, but the principle is the same.

**Comment by skyne98** [comment]
So, your suggestion is to avoid using the implementations provided by bootloader and instead use alternative frame allocator?

**Comment by phil-opp** [comment]
Yes. The [FrameAllocator](https://github.com/rust-osdev/bootloader/blob/81cb282d549842d52a3865ec5eef60a9745bb001/src/frame_allocator.rs#L4) of the bootloader is only `pub(crate)` anyway, so it shouldn't be available to the kernel.

**Comment by phil-opp** [comment]
I think this is resolved and can be closed. I'm happy to reopen this if I missed any unresolved issues!
