### ISSUE TITLE
Recursive Index in page tables?

### ISSUE THREAD

**Issue by mark-i-m** [rust-osdev/bootloader#88]
Is it always index `0`? Should this be passed in the `BootInfo` struct?

**Comment by phil-opp** [comment]
We used to hardcode the index to `511`, but this changed with #71. Now we dynamically look for a free level 4 entry. The chosen index is indirectly reported through the `recursive_page_table_addr` field in the `BootInfo`:

https://github.com/rust-osdev/bootloader/blob/90f5b8910d146d6d489b70a6341d778253663cfa/src/bootinfo/mod.rs#L32-L34

It shouldn't be `0`, however, because the bootloader maps itself to that slot…

**Comment by mark-i-m** [comment]
Thanks! I eventually figured that out. Perhaps a "get recursive index" method could be added that just masks out bits 21:12 and returns a PageTableIndex?

**Comment by phil-opp** [comment]
Sure, I'd be happy to merge a pull request for this.
